<a href="https://colab.research.google.com/github/BugBusterBoy/pytorchproj/blob/main/00_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


Intro to Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim #no dimension

0

In [5]:
#Get tensor back as Python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([8,9])
vector

tensor([8, 9])

In [8]:
vector.ndim #vector has 1 dimension

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [14]:
MATRIX[0]
MATRIX[1]
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
[3,6,9],
[2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [19]:
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0][1]

tensor([3, 6, 9])

In [24]:
### Random tensors
# Important because many neural networks learn by tensors full of random numbers

#Start with random --> look at data -> update random numbers -> look at data -> update random numbers

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1242, 0.3359, 0.1479, 0.7445],
        [0.0222, 0.5295, 0.0877, 0.8272],
        [0.3987, 0.0491, 0.0706, 0.7613]])

In [25]:
random_tensor.ndim

2

In [27]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3,224,224))
#color RGB, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [30]:
#Zeros and ones
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype #default datatype

torch.float32

In [41]:
# Create a range of tensors and tensors-like
one_to_ten = torch.arange(0,11,1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# Creaing tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])